// Augment the Cloudflare.Env interface with our wrangler-registered secrets.
// Kept separate from worker-configuration.d.ts (which is auto-regenerated by
// `wrangler types` and loses manual edits).

declare namespace Cloudflare {
	interface Env {
		// AES-GCM 256-bit key (base64) for OAuth token encryption.
		// Registered via: wrangler secret put OAUTH_ENC_KEY
		OAUTH_ENC_KEY: string;

		// Google OAuth 2.0 Client ID — <id>.apps.googleusercontent.com
		// Not inherently secret but registered via wrangler secret for uniformity.
		GOOGLE_OAUTH_CLIENT_ID: string;

		// Google OAuth 2.0 Client Secret.
		// Registered via: wrangler secret put GOOGLE_OAUTH_CLIENT_SECRET
		GOOGLE_OAUTH_CLIENT_SECRET: string;

		// Shared secret for the weasley-clock cron dispatcher. The worker's
		// scheduled() handler sends it as X-Sync-Secret; the plugin route
		// rejects if missing/mismatched.
	}
}

export {};
